// <auto-generated />
using System;
using GraduationQRSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraduationQRSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("GraduationQRSystem.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AttendanceTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAttended")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeniorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuestId");

                    b.HasIndex("SeniorId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("GraduationQRSystem.Models.Senior", b =>
                {
                    b.Property<int>("SeniorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QrUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("SeniorId");

                    b.ToTable("Seniors");
                });

            modelBuilder.Entity("GraduationQRSystem.Models.Guest", b =>
                {
                    b.HasOne("GraduationQRSystem.Models.Senior", "Senior")
                        .WithMany("Guests")
                        .HasForeignKey("SeniorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Senior");
                });

            modelBuilder.Entity("GraduationQRSystem.Models.Senior", b =>
                {
                    b.Navigation("Guests");
                });
#pragma warning restore 612, 618
        }
    }
}
